### ISSUE TITLE
On Japanese or French systems run command via DatabaseTransport fails with ibm_db_dbi::Error

### ISSUE THREAD

**Issue by LiJunBJZhu** [IBM/python-itoolkit#63]
* **itoolkit version**: python3-itoolkit-1.6.1-1.ppc64
* **Python version**:  python3-3.6.10-2.ppc64
* **OS Name and Version**: 7.2 Japanese, 7.3 French
* **IBM i version**:  7.2 Japanese, 7.3 French
* **XMLSERVICE version**:  XML Toolkit 1.9.9.3

**Describe the bug**

**Code**

conn = dbi.connect()
itool = iToolKit()
itransport = DatabaseTransport(conn)
itool.add(iCmd('command1', command, {'error': 'on'}))
itool.call(itransport)
command_output = itool.dict_out('command1')

**Error**
For example, calling the above code to  run CL command "DLTLIB LIB(NOTEXISTS)", then an error is reported as below. The error doesn't appear on English system.

Traceback (most recent call last):
 File "/tmp/ansible_ibmi_object_save_payload_bwwr4eug/ansible_ibmi_object_save_payload.zip/ansible/module_utils/ibmi/ibmi_util.py", line 173, in itoolkit_run_command
 File "/QOpensys/pkgs/lib/python3.6/site-packages/itoolkit/itoolkit.py", line 1155, in call
  xml_out = itrans.call(self)
 File "/QOpensys/pkgs/lib/python3.6/site-packages/itoolkit/transport/database.py", line 66, in call
  return "".join(row[0] for row in cursor).rstrip('\0')
 File "/QOpensys/pkgs/lib/python3.6/site-packages/itoolkit/transport/database.py", line 66, in <genexpr>
  return "".join(row[0] for row in cursor).rstrip('\0')
 File "/QOpensys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1128, in __next__
  row = self.fetchone()
 File "/QOpensys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1492, in fetchone
  row_list = self._fetch_helper(1)
 File "/QOpensys/pkgs/lib/python3.6/site-packages/ibm_db_dbi.py", line 1476, in _fetch_helper
  raise self.messages[-1]
ibm_db_dbi.Error: ibm_db_dbi::error: SystemError('<built-in function fetch_tuple> returned a result with an error set',)

Have no idea why the <built-in function fetch_tuple> can't be displayed on the git issue. So put a snapshot here.
<img width="572" alt="图片" src="https://user-images.githubusercontent.com/13618961/83818041-e4444100-a6f8-11ea-8221-d18a845b0f2b.png">

**Comment by LiJunBJZhu** [comment]
python3-ibm_db-2.0.5.12-0.ppc64

**Comment by kadler** [comment]
Sorry I have taken so long to respond. Is this still an issue?
