### ISSUE TITLE
Running itool.call ends the program and does nothing

### ISSUE THREAD

**Issue by deydist** [IBM/python-itoolkit#81]
* **itoolkit version**:  1.7.2
* **Python version**:   3.11.0
* **OS Name and Version**:  Windows 11
* **IBM i version**:  V7R4M0
* **XMLSERVICE version**:  Not sure how to check this on Windows.

**Describe the bug**

When I run the below code, it runs up to the 'itool.call(itransport)', then the run just stops with no output. Only the "print("Stops right after this...")" gets displayed on the terminal. Something is causing the call to just die with no errors. My connection to i Series is good and succeeds.  "print(itransport.procedure)" returns "QXMLSERV.iPLUGR512K"

```
from itoolkit import *
from itoolkit.transport import DatabaseTransport
import pyodbc

system = f"DSN=DSN_AS400;UID=user;PWD=password"

conn = pyodbc.connect(system)
itransport = DatabaseTransport(conn)
itool = iToolKit()

itool.add(iCmd5250('wrkactjob', 'WRKACTJOB'))
print("Stops right after this...")
itool.call(itransport)
print("This doesn't run...")
wrkactjob = itool.dict_out('wrkactjob')

print(wrkactjob)
```

**Comment by kadler** [comment]
Can you try printing out the job name and looking at the job log, eg.

```python
conn = pyodbc.connect(system)

job_name = conn.cursor().execute("select job_name from sysibm.sysdummy1").fetchval()
print(f"DB job name is {job_name}")

itransport = DatabaseTransport(conn)
itool = iToolKit()

itool.add(iCmd5250('wrkactjob', 'WRKACTJOB'))
print("Stops right after this...")
itool.call(itransport)
# get job log while it's stuck
```

**Comment by deydist** [comment]
> Can you try printing out the job name and looking at the job log, eg.
> 
> ```python
> conn = pyodbc.connect(system)
> 
> job_name = conn.cursor().execute("select job_name from sysibm.sysdummy1").fetchval()
> print(f"DB job name is {job_name}")
> 
> itransport = DatabaseTransport(conn)
> itool = iToolKit()
> 
> itool.add(iCmd5250('wrkactjob', 'WRKACTJOB'))
> print("Stops right after this...")
> itool.call(itransport)
> # get job log while it's stuck
> ```

I get "580340/QUSER/QZDASOINIT" as a job name for example but in i series it cannot find the job using commands 
DSPSPLF FILE(QPJOBLOG) JOB(580340/QUSER/QZDASOINIT) or dspjoblog job(580340/QUSER/QZDASOINIT)

Nor do any of the job#s show in dspjoblog job(QUSER/QZDASOINIT)

**Comment by deydist** [comment]
I was able to step into the call function and followed it to the below exception thrown... 


Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 213, in resolve
    return dict[key]
           ~~~~^^^^^
KeyError: 'cmds_to_add_back'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1893, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 242, in getVariable
    var = resolver.resolve(var, k)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'cmds_to_add_back'

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 213, in resolve
    return dict[key]
           ~~~~^^^^^
KeyError: 'childNodes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1893, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 242, in getVariable
    var = resolver.resolve(var, k)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'childNodes'

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 213, in resolve
    return dict[key]
           ~~~~^^^^^
KeyError: 'node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1893, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 242, in getVariable
    var = resolver.resolve(var, k)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'node'

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 213, in resolve
    return dict[key]
           ~~~~^^^^^
KeyError: 'writer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1893, in do_it
    var_obj = pydevd_vars.getVariable(self.thread_id, self.frame_id, scope, attrs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_vars.py", line 242, in getVariable
    var = resolver.resolve(var, k)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 2022.3.1\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_resolver.py", line 215, in resolve
    return getattr(dict, key)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'writer'

**Comment by kadler** [comment]
Ohh, I misunderstood. In your code you had a comment "Stops right after this..." and I assumed that you meant that it hung, but it sounds now like the code actually exits/crashes instead.

Unfortunately, your traceback doesn't look like it's coming from itoolkit, but from PyCharm. All the files mentioned are in PyCharm files and I recognize any of the code that it mentions.

Are you able to run your program from the command line outside of PyCharm? If so, please provide any traceback which results.

**Comment by deydist** [comment]
> Ohh, I misunderstood. In your code you had a comment "Stops right after this..." and I assumed that you meant that it hung, but it sounds now like the code actually exits/crashes instead.
> 
> Unfortunately, your traceback doesn't look like it's coming from itoolkit, but from PyCharm. All the files mentioned are in PyCharm files and I recognize any of the code that it mentions.
> 
> Are you able to run your program from the command line outside of PyCharm? If so, please provide any traceback which results.

Ah, sorry for the confusion. I can run it from the cmd line but the only output is "Stops right after this..." So the program just exits without any exceptions.

I stepped through using Pdb and it appears the program exists at the below line 
(Pdb) n
> c:\python311\lib\site-packages\itoolkit\itoolkit.py(1173)call()
**-> xml_out = itrans.call(self)**
(Pdb) n

_Here the program exists back to command line prompt after trying to run next line (n)_

**Comment by kadler** [comment]
```
    from xml.dom import expatbuilder
  File "<frozen importlib._bootstrap>", line 1175, in _find_and_load
  File "<frozen importlib._bootstrap>", line 171, in __enter__
  File "<frozen importlib._bootstrap>", line 123, in acquire
KeyError: 16544
```

Looks like it can't find xml.dom.expatbuilder, which is part of the Python xml.dom package. Is something wrong with your Python installation somehow?

**Comment by deydist** [comment]
> ```
>   File "C:\Python311\Lib\xml\dom\minidom.py", line 1999, in parseString
>     from xml.dom import expatbuilder
>   File "<frozen importlib._bootstrap>", line 1175, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 171, in __enter__
>   File "<frozen importlib._bootstrap>", line 123, in acquire
> KeyError: 16544
> ```
> 
> Looks like it can't find xml.dom.expatbuilder, which is part of the Python xml.dom package. Is something wrong with your Python installation somehow?

Strange... there must be. I was able to run all of this on a different machine. Wonder if my django project is causing some conflict or something. I really appreciate you helping me get to the bottom of this.
